[package]
name = "r_os"
version = "0.1.0"
edition = "2018"
authors = ["victor"]

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
