name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-system-x86
    - name: Run build
      run: cargo build
    - name: Run clippy
      run: cargo clippy
    - name: Run build image
      run: cargo install bootimage &&
           rustup component add llvm-tools-preview &&
           cargo bootimage
    - name: Test
      run: cargo test
